config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :api do
    namespace :v1 do
      resources :tasks
      resources :categories
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :task_categories, dependent: :destroy
    has_many :tasks, through: :task_categories
    scope :search_by_name, -> (name) { where("name LIKE ?", "%#{name}%") }

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "name", "updated_at"]
    end
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :task_categories, dependent: :destroy
    has_many :categories, through: :task_categories
    validates :name, presence: true
    validates :deadline, presence: true
    validates :priority, presence: true
    validates :status, presence: true

    enum status: {
        not_started: 0, # 未着手
        in_progress: 1, # 着手中
        completed: 2    # 完了
    }
    def  disp_name
        "#{name}です"
    end

    def self.ransackable_attributes(auth_object = nil)
        self.attribute_names
    end

    def self.ransackable_associations(auth_object = nil)
        self.attribute_names
    end
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
  belongs_to :task
  belongs_to :category
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :update, :destroy]

    PER_PAGE = 5

    def index
        @categories = Category.all
        @categories = @categories.where("name LIKE ?", "%#{params[:name]}%") if params[:name].present?
        @categories = @categories.page(params[:page]).per(PER_PAGE)

        render json: @categories
    end

    def show
        render json: @category
    end

    def create
        @category = Category.new(category_params)

        if @category.save
        render json: @category, status: :created
        else
        render json: @category.errors, status: :unprocessable_entity
        end
    end

    def update
        if @category.update(category_params)
        render json: @category
        else
        render json: @category.errors, status: :unprocessable_entity
        end
    end

    def destroy
        @category.destroy
        head :no_content
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    PER_PAGE = 5

    def index
      tasks = Task.order(id: :asc).where.not(status: :completed)
      q = Task.ransack(params[:q])
      tasks = q.result.where.not(status: :completed).order(id: :asc).page(params[:page]).per(PER_PAGE)
      render json: tasks
    end

    def show
      render json: @task, serializer: TaskSerializer
    end

    def create
      @task = Task.new(task_params)
      category_ids = params[:task][:category_ids].reject(&:blank?)
      @task.category_ids = category_ids
      if @task.save
        render json: @task, serializer: TaskSerializer, status: 201
      else
        render json: { errors: @task.errors.full_messages }, status: 422
      end
    end

    def update
      if @task.update(task_params)
        render json: @task, serializer: TaskSerializer
      else
        render json: { errors: @task.errors.full_messages }, status: 422
      end
    end

    def destroy
      @task.destroy!
      head :no_content
    end

    private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :deadline, :priority, :status, category_ids: [], category_names: [])  
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  
    private
  
    def record_not_found
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
end
  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: %i[show edit update destroy]

    PER_PAGE = 5
  
    def index
      @categories = Category.all
      @categories = @categories.search_by_name(params[:name]) if params[:name].present?
      @categories = @categories.page(params[:page]).per(PER_PAGE)
    end
  
    def show
    end
  
    def new
      @category = Category.new
    end
  
    def edit
    end
  
    def create
      @category = Category.new(category_params)
  
      if @category.save
        redirect_to @category, notice: '作成しました'
      else
        render :new
      end
    end
  
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Taskを更新しました'
      else
        render :edit
      end
    end
  
    def destroy
      @category.destroy
      redirect_to categories_path, notice: '削除しました'
    end
  
    private
  
    def set_category
      @category = Category.find(params[:id])
    end
  
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  PER_PAGE = 5

  def index
    @q = Task.ransack(params[:q])
    @tasks = @q.result.not_completed.order(id: :asc).eager_load(:categories).page(params[:page]).per(PER_PAGE)
  end

  def show
  end 

  def new
    @task = Task.new
    @task.deadline ||= 1.week.from_now
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task, notice: "作成しました"
    else
      render :new, status: 422
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: "Taskを更新しました"
    else
      render :edit, status: 422
    end
  end

  def destroy
    @task.destroy!
    redirect_to root_path, alert: "削除しました"
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :deadline, :priority, :status, category_ids: [])  
  end
  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render "layouts/error_messages_category" %>
<%= form_with model: category, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit (action_name == 'new' ? '登録' : '更新') %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>編集</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<%= form_tag(categories_path, method: :get) do %>
  <%= label_tag(:name, "カテゴリ名") %>
  <%= text_field_tag(:name, params[:name], placeholder: "キーワードを入力") %>
  <%= submit_tag("検索") %>
<% end %>

<h1>カテゴリ一覧</h1>
<table>
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">カテゴリ名</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each.with_index(1) do |category, i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= category.name %></td>
        <td>
          <%= link_to "詳細", category %>
          <%= link_to "編集", edit_category_path(category) %>
          <%= button_to "削除", category_path(category), method: :delete, data: { confirm: "削除しますか?" }%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<div><%= link_to "登録", new_category_path %></div>

<%= paginate @categories %>

app/views/categories/new.html.erb
<h1>カテゴリ 登録</h1>
<%= render 'form', categorie: @categories %>

app/views/categories/show.html.erb
<h1>カテゴリ詳細</h1>
<p>カテゴリ名　<%= @category.name %></p>

app/views/layouts/_error_messages.html.erb
<% if @task.errors.any? %>
  <div>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><span style="color: red;"><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_messages_category.html.erb
<% if @category.errors.any? %>
  <div>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><span style="color: red;"><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <p style="color: <%= flash_type == 'notice' ? 'green' : 'red' %>;"><%= msg %></p>
  <hr>
<% end %>

app/views/layouts/_form.html.erb
<%= form_with model: @task, local: true do |form| %>
  <div>
    <%= form.label :name, "Todo名" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit (action_name == 'new' ? '登録' : '更新') %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="point">
  <%= link_to "タスク一覧", tasks_path %>
  <%= link_to "カテゴリ一覧", categories_path %>
    <hr>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= render "layouts/error_messages" %>
<%= form_with model: task, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
    <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :category_ids, 'カテゴリ名' %>
    <%= form.collection_select :category_ids, Category.all, :id, :name, {}, { multiple: true } %>
  </div>
<%= form.label :deadline %>
<%= form.text_field :deadline, value: @task.deadline.present? ? @task.deadline.strftime("%Y-%m-%d ") : ''%>
  <div>
    <%= form.label :priority %>
    <%= form.text_field :priority %>
  </div>
  <div>
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div> 
  <div>
    <%= form.submit (action_name == 'new' ? '登録' : '更新') %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>編集</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :name_or_description_cont, "タスク名" %>
  <%= f.search_field :name_or_description_cont %>
  <%= f.submit "検索" %>
<% end %>

<th><%= sort_link(@q, :deadline, "終了期限" )%></th>
<th><%= sort_link(@q, :priority, "優先順位" )%></th>

<h1>タスク一覧</h1>
<table>
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">タスク名</th>
      <th scope="col">タスク説明</th>
      <th scope="col">カテゴリ名</th>
      <th scope="col">終了期限</th>
      <th scope="col">優先順位</th>
      <th scope="col">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each.with_index(1) do |task, i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td>
        <% task.categories.each do |category| %>
            <%= category.name %>
        <% end %>
        </td>
        <td><%= task.deadline.strftime("%Y-%m-%d") %></td>
        <td><%= task.priority %></td>
        <td><%= task.status %></td>
        <td>
          <%= link_to "詳細", task %>
          <%= link_to "編集", edit_task_path(task) %>
          <%= button_to "削除", task_path(task), method: :delete, data: { confirm: "削除しますか?" }%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div><%= link_to "登録", new_task_path %></div>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>Todo 登録</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Todo詳細</h1>
<p>タスク名　<%= @task.name %></p>
<p>タスク説明　<%= @task.description %></p>
<p>カテゴリ名　
<% @task.categories.each do |category| %>
  <%= category.name %>
<% end %>
</p>
<p>終了期限　<%= @task.deadline.strftime("%Y-%m-%d") %></p>
<p>優先順位　<%= @task.priority %></p>
<p>ステータス　<%= @task.status %></p>